[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed  = 921600
monitor_speed = 921600
build_flags   = -DCORE_DEBUG_LEVEL=3

lib_deps =
  adafruit/Adafruit INA219@^1.2.3
  madhephaestus/ESP32Encoder@^0.10.1
